name: Extract PDF pages
on: [workflow_dispatch]
jobs:
  extract_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: apt-get -y install imagemagick ghostscript
      - name: Extract Page Images
        run: magick -density 300 docs/example.pdf -quality 85 docs/example-%d.jpg
      - name: Commit Change
        run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add docs
            git commit -m "Added extracted page"
            git push origin master
